development:
    adapter: postgresql
    host: localhost
    port: 5432
    username: gerhardk19
    password: rails
    database: battleships_development

production:
    adapter: postgresql
    host: localhost
    port: 5432
    username: gerhardk19
    password: rails
    database: battleships_development

test:
    adapter: postgresql
    host: localhost
    port: 5432
    username: gerhardk19
    password: 
    database: battleships_test

